name: yiwucloud
description: A new Flutter project.
publish_to: 'none'

version: 1.0.49+50

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  http: ^0.13.5
  shimmer: ^2.0.0
  firebase_core: ^2.3.0
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.1.2
  permission_handler: ^10.2.0
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil: ^5.6.0
  avatars: ^3.0.2
  flutter_bloc: ^8.1.2
  package_info_plus: ^3.0.3
  flutter_custom_clippers: ^2.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  photo_view: ^0.14.0
  flutter_form_builder: ^9.1.0
  connectivity_plus: ^4.0.0
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.11
  rxdart: ^0.27.7
  audioplayers: ^4.0.1
  loader_overlay: ^2.2.0
  dropdown_button2: ^2.1.2
  percent_indicator: ^4.2.3
  syncfusion_flutter_datepicker: ^21.2.3
  flutter_datetime_picker: ^1.5.1
  accordion: ^2.5.1
  expandable_text: ^2.3.0
  flutter_datawedge: ^1.2.0
  device_info_plus: ^9.0.2
  geolocator: ^9.0.2
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.1
  flutter_exif_rotation: ^0.5.1
  image_cropper: ^4.0.1
  flutter_cached_pdfview: ^0.4.2
  share_plus: ^7.1.0
  hive: ^2.2.3
  path_provider: ^2.1.0
  styled_text: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: 2.0.1
  build_runner: ^2.4.6



flutter:
  assets:
    - assets/img/
    - assets/sounds/
  uses-material-design: true
