// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBHmbbGsu30O8ddxpx-B9j6RzQBzmHf_g',
    appId: '1:116316009624:android:bb7585e4e78f095c21cced',
    messagingSenderId: '116316009624',
    projectId: 'yiwucloud',
    storageBucket: 'yiwucloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMFzzX0C_tKTwPM_ZJKiHYLR1-CIO0nY',
    appId: '1:116316009624:ios:2247f91555617f7a21cced',
    messagingSenderId: '116316009624',
    projectId: 'yiwucloud',
    storageBucket: 'yiwucloud.appspot.com',
    iosClientId: '116316009624-tc8mo38fegcroapkql3t2n4esuittodl.apps.googleusercontent.com',
    iosBundleId: 'com.yiwu.yiwucloud.yiwucloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMFzzX0C_tKTwPM_ZJKiHYLR1-CIO0nY',
    appId: '1:116316009624:ios:2247f91555617f7a21cced',
    messagingSenderId: '116316009624',
    projectId: 'yiwucloud',
    storageBucket: 'yiwucloud.appspot.com',
    iosClientId: '116316009624-tc8mo38fegcroapkql3t2n4esuittodl.apps.googleusercontent.com',
    iosBundleId: 'com.yiwu.yiwucloud.yiwucloud',
  );
}
